# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Jaspreet Kamra
title: FUTURE LAWYER
email: jaspreetkamra1998@gmail.com
#phone: Your phone number (optional)
#cv   : "resume.pdf"
#website: Your website (eg. https://google.com)(optional)

# Social links
#twitter_username: jekyllrb
github_username:  Jazz-Kamra
#dribbble_username: jekyll
facebook_username: facebook
#flickr_username: jekyll
instagram_username: instagram
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hey I'm jazz and I'm this not so crazy girl who's on her way to be insanely successful (fingers crossed) lawyer. 

  Some facts about me:

  - I love working out
  - I am a Potterhead
  - I make the best **Tea** and **Chicken Masala** in the world
  - I've a published paper

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: My Bucket List #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  The few of the long list of things i wanna do before i die are:

  - Donate 1 cr to an NGO
  - Put all my friends in a private jet and take them to bora bora to chill
  - Be a fitness model
  - Travel to space

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
